version: '3'

services:
    web:
        container_name: web
        build: .
        restart: always
        volumes:
            - .:/usr/src/app
        ports:
            - 8080:3000
        command: npm run start